### ISSUE TITLE
Asynchronous option

### ISSUE THREAD

**Issue by Marius-Romanus** [capacitor-community/android-security-provider#3]
Hello, from my total ignorance of installIfNeeded, but wouldn't it be better to do it asynchronously so as not to block the layout, taking into account that this would have to be done when starting the app?

https://developer.android.com/training/articles/security-gms-provider?hl=es-419#example_async

I find it very interesting, everything that is to improve security! Greetings!

**Comment by dtarnawsky** [comment]
Capacitor make its calls into native land asynchronously already, so if the plugin also used async method it would not improve the performance. The advice from that article is definitely relevant if you are building a purely native app though.
